#
# NVreg_DynamicPowerManagement=0x02 - Enables the use of dynamic power
# management for Turing generation mobile cards, allowing the dGPU to be
# powered down during idle time.
#
options nvidia NVreg_DynamicPowerManagement=0x02
