#
## Chromium flags
#

--disable-crash-reporter

# Security
--enable-webrtc-hide-local-ips-with-mdns
--disable-reading-from-canvas
--reduced-referrer-granularity
--strict-origin-isolation
--disallow-doc-written-script-loads

# Misc
--enable-webrtc-pipewire-capturer
--enable-native-notifications
--password-store=basic
--disk-cache-dir=/run/user/1000/chromium-cache
--force-device-scale-factor=1.0
--scroll-pixels=150
--enable-send-tab-to-self
--lang=en
--ozone-platform=wayland

--enable-features=UseOzonePlatform,WebUIDarkMode
--disable-features=HappinessTrackingSurveysForDesktop,HappinessTrackingSurveysForDesktopDemo,HappinessTrackingSurveysForDesktopSettings,HappinessTrackingSurveysForDesktopSettingsPrivacy,TabHoverCardImages,TabHoverCards
